general {
  uid = "root"
  logfile = "/dev/null"
  loglevel = debug
  db_path = "/var/cache/owntone/songs3.db"
  cache_path = "/var/cache/owntone/cache.db"
  bind_address = "0.0.0.0"
}

library {
  name = "Mentat"
  port = 3689

  # Watch this directory for .pipe FIFOs (lr.pipe, all.pipe)
  directories = { "/srv/pipes" }

  # Automatically start playing a pipe when librespot writes to it
  pipe_autostart = true
}
